"""
dual_stream_gnn.py — Dual-stream (raw + diff-norm) GNN experiment.

Idea B: feed both raw DSPSS and difference-normalised DSPSS as separate node
feature channels so the GNN can learn their complementarity.

Node features: [x, y, z, dspss_diff, dspss_raw]  (in_channels=5)

Design rationale
----------------
- diff-norm removes hole-edge background → clean defect signal, depth discrimination
- raw carries absolute stress level → hole-edge geometry cue, no baseline needed
- At inference without baseline: zero the diff channel (→ model falls back to raw)
- No change to any existing architecture: just pass in_channels=5

Prerequisites on Vancouver
--------------------------
1. Generate plain (raw) z-score data:
       python data_prep/prepare_plain_zscore.py
   This creates:  GNN/GNN_hole_2026/all_hole_defect_zscore/{train,val,test}/

2. Run this script:
       python dual_stream_gnn.py --train
       python dual_stream_gnn.py --eval --no_baseline   # simulate baseline-free

Usage
-----
    python dual_stream_gnn.py --train --arch hybridmgn
    python dual_stream_gnn.py --eval  --ckpt <path>
    python dual_stream_gnn.py --eval  --ckpt <path> --no_baseline
    python dual_stream_gnn.py --test   # unit tests

Author: Nishioka (2026-06)
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import List, Optional, Tuple

import numpy as np
import torch
from torch_geometric.data import Data, Dataset
from torch_geometric.loader import DataLoader

# ── repo path ────────────────────────────────────────────────────────────────
_HERE = Path(__file__).parent.resolve()
REPO = Path("/home/nishioka/GNN/wccm2026-cfrp-gnn")
if not REPO.is_dir():
    REPO = _HERE
sys.path.insert(0, str(REPO))
import train as T   # noqa: E402

# ── default paths (Vancouver layout) ─────────────────────────────────────────
GD = Path("/home/nishioka/GNN")

DIR_DIFF = GD / "GNN_hole_2026/all_sub_hole_defect_zscore"   # diff-norm (existing)
DIR_RAW  = GD / "GNN_hole_2026/all_hole_defect_zscore"        # raw z-score (generated by prepare_plain_zscore.py)
DIR_LBL  = GD / "GNN_hole_2026/all_19class_label"
DIR_COORD = GD / "GNN_hole/GNN_hole_data"

CK_OUT = GD / "GNN_hole_2026/GNN_model/dual_stream"

N_NODES = 13942


# ─────────────────────────────────────────────────────────────────────────────
# Data loading
# ─────────────────────────────────────────────────────────────────────────────

def _load_coords() -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    x = np.load(DIR_COORD / "normalized_x_2layer.npy")[:N_NODES]
    y = np.load(DIR_COORD / "normalized_y_2layer.npy")[:N_NODES]
    z = np.load(DIR_COORD / "normalized_z_2layer.npy")[:N_NODES]
    return x, y, z


def _load_edges() -> torch.Tensor:
    edges = np.load(DIR_COORD / "hole_edges_2layer_best.npy")
    return torch.tensor(edges, dtype=torch.long)


def build_dual_data(
    split: str,
    no_baseline: bool = False,
    noise_std: float = 0.0,
    noise_healthy_std: float = 0.0,
    baseline_noise_std: float = 0.0,
    diff_channel_dropout: float = 0.0,
) -> List[Data]:
    """
    Load {train, val, test} specimens with 5-channel node features:
        [x, y, z, dspss_diff, dspss_raw]

    Parameters — noise augmentation ("strongest model")
    ----------
    split                 : 'train' | 'val' | 'test'
    no_baseline           : zero both DSPSS channels (baseline-free inference)
    noise_std             : measurement noise on defective specimens (both channels)
    noise_healthy_std     : noise added to raw of healthy specimens (class-0 nodes)
                            → makes Stage-0 robust when the healthy reference is noisy
    baseline_noise_std    : perturb the diff channel by N(0, σ²) PER SPECIMEN
                            → simulates imperfect/noisy 1st-flight baseline
    diff_channel_dropout  : probability [0,1] to zero the diff channel for a specimen
                            → forces model to learn from raw alone (no-baseline robustness)
    """
    diff_dir = DIR_DIFF / split
    raw_dir  = DIR_RAW  / split
    lbl_dir  = DIR_LBL

    if not raw_dir.is_dir():
        raise FileNotFoundError(
            f"Raw z-score data not found at {raw_dir}.\n"
            f"Generate it first:  python data_prep/prepare_plain_zscore.py"
        )

    cx, cy, cz = _load_coords()
    edge_index  = _load_edges()

    coord_block = np.column_stack([cx, cy, cz])   # (N, 3)

    files = sorted(f for f in os.listdir(diff_dir) if f.endswith(".npy"))
    data_list: List[Data] = []
    is_train = (split == "train")

    for fname in files:
        lbl_fname = fname.replace(".npy", "_19label.npy")
        lbl_path  = lbl_dir / lbl_fname
        if not lbl_path.exists():
            continue

        diff_vals = np.load(diff_dir / fname)[:N_NODES].astype(np.float32)
        label     = np.load(lbl_path)[:N_NODES]

        # raw channel — use zero if no_baseline or file missing
        raw_path = raw_dir / fname
        if no_baseline or not raw_path.exists():
            raw_vals  = np.zeros(N_NODES, dtype=np.float32)
            diff_vals = np.zeros(N_NODES, dtype=np.float32)
        else:
            raw_vals = np.load(raw_path)[:N_NODES].astype(np.float32)

        if is_train:
            # 1. Measurement noise on both channels (defective specimens)
            if noise_std > 0.0:
                diff_vals = diff_vals + np.random.normal(0, noise_std, N_NODES).astype(np.float32)
                raw_vals  = raw_vals  + np.random.normal(0, noise_std, N_NODES).astype(np.float32)

            # 2. Healthy-node noise: add extra noise to class-0 nodes in raw
            #    Simulates the case where the "healthy reference" used for Stage-0
            #    fitting is itself noisy — teaches Stage-0 to be noise-robust.
            if noise_healthy_std > 0.0:
                lbl_for_mask = label[:N_NODES].astype(np.int32)
                if lbl_for_mask.ndim == 2:
                    lbl_for_mask = lbl_for_mask.argmax(axis=1)
                healthy_mask = (lbl_for_mask == 0).astype(np.float32)
                hn = np.random.normal(0, noise_healthy_std, N_NODES).astype(np.float32)
                raw_vals = raw_vals + hn * healthy_mask

            # 3. Baseline noise: perturb the diff channel to simulate imperfect baseline
            #    diff_measured = raw - (baseline_true + ε),  ε ~ N(0, σ_bl²)
            if baseline_noise_std > 0.0 and not no_baseline:
                bl_noise  = np.random.normal(0, baseline_noise_std, N_NODES).astype(np.float32)
                diff_vals = diff_vals - bl_noise   # subtract baseline perturbation

            # 4. Channel dropout: randomly zero the diff channel for this specimen
            #    Forces the model to also be capable of prediction from raw alone.
            if diff_channel_dropout > 0.0 and np.random.rand() < diff_channel_dropout:
                diff_vals = np.zeros(N_NODES, dtype=np.float32)

        # node features: [x, y, z, diff, raw]
        feats = np.column_stack([coord_block, diff_vals, raw_vals])  # (N, 5)
        x_t   = torch.tensor(feats, dtype=torch.float)

        # labels
        lbl_t = torch.tensor(label, dtype=torch.float)
        if lbl_t.ndim == 2 and lbl_t.shape[1] > 1:
            y = torch.argmax(lbl_t, dim=1).long()
        else:
            y = lbl_t.long().squeeze()

        d = Data(x=x_t, edge_index=edge_index, y=y)
        d.filename = fname
        data_list.append(d)

    print(f"[dual] split={split}  loaded={len(data_list)}  "
          f"no_baseline={no_baseline}  in_channels=5")
    return data_list


# ─────────────────────────────────────────────────────────────────────────────
# Architecture wrapper  (thin: just overrides in_channels)
# ─────────────────────────────────────────────────────────────────────────────

def build_model(arch: str, device: torch.device) -> torch.nn.Module:
    """
    Reuse existing architectures from train.py with in_channels=5.
    The only change: the first linear layer is wider by one input.
    """
    model = T.build_model(arch=arch, in_channels=5)
    return model.to(device)


# ─────────────────────────────────────────────────────────────────────────────
# Training loop (minimal — delegates metrics to train.py helpers)
# ─────────────────────────────────────────────────────────────────────────────

def train_dual(args: argparse.Namespace) -> None:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[dual] device={device}  arch={args.arch}")

    train_data = build_dual_data(
        "train",
        noise_std=args.noise_std,
        noise_healthy_std=args.noise_healthy_std,
        baseline_noise_std=args.baseline_noise_std,
        diff_channel_dropout=args.diff_channel_dropout,
    )
    val_data   = build_dual_data("val")

    train_loader = DataLoader(train_data, batch_size=args.batch_size, shuffle=True,  num_workers=4)
    val_loader   = DataLoader(val_data,   batch_size=args.batch_size, shuffle=False, num_workers=4)

    model     = build_model(args.arch, device)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)
    criterion = torch.nn.CrossEntropyLoss()

    best_f1   = 0.0
    CK_OUT.mkdir(parents=True, exist_ok=True)
    ckpt_path = CK_OUT / f"{args.arch}_dual_best.pth"

    for epoch in range(1, args.epochs + 1):
        model.train()
        total_loss = 0.0
        for batch in train_loader:
            batch = batch.to(device)
            optimizer.zero_grad()
            out  = model(batch)
            loss = criterion(out, batch.y)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        scheduler.step()

        if epoch % args.eval_every == 0:
            f1 = _eval_f1(model, val_loader, device)
            print(f"  epoch {epoch:3d}  loss={total_loss/len(train_loader):.4f}  val_macro_F1={f1:.4f}")
            if f1 > best_f1:
                best_f1 = f1
                torch.save(model.state_dict(), ckpt_path)
                print(f"    → saved  {ckpt_path}  (best={best_f1:.4f})")

    print(f"[dual] training done.  best_val_F1={best_f1:.4f}")


def _eval_f1(model, loader, device) -> float:
    from sklearn.metrics import f1_score
    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch in loader:
            batch = batch.to(device)
            pred  = model(batch).argmax(dim=1)
            y_true.extend(batch.y.cpu().numpy())
            y_pred.extend(pred.cpu().numpy())
    return float(f1_score(y_true, y_pred, average="macro", zero_division=0))


def eval_dual(args: argparse.Namespace) -> None:
    device    = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    test_data = build_dual_data("test", no_baseline=args.no_baseline)
    loader    = DataLoader(test_data, batch_size=args.batch_size, shuffle=False, num_workers=4)

    model = build_model(args.arch, device)
    state = torch.load(args.ckpt, map_location=device)
    model.load_state_dict(state)
    model.eval()

    f1 = _eval_f1(model, loader, device)
    mode = "no-baseline (raw only)" if args.no_baseline else "full dual (raw+diff)"
    print(f"[dual] eval  mode={mode}  macro_F1={f1:.4f}")

    # comparison baseline
    print("[dual] reference F1s from RESULTS.md:")
    print("  raw DSPSS (current WCCMtalk): 0.61")
    print("  diff-norm HybridMGN (standalone): 0.792")
    print("  diff-norm + Stage-0: 0.803")
    print(f"  THIS RUN ({mode}): {f1:.4f}")


# ─────────────────────────────────────────────────────────────────────────────
# Unit tests
# ─────────────────────────────────────────────────────────────────────────────

def _tests() -> None:
    print("[test] Checking dual_stream_gnn imports and data shape logic...")

    # Synthetic node feature check: 5 channels
    N = 13942
    cx = np.random.randn(N).astype(np.float32)
    cy = np.random.randn(N).astype(np.float32)
    cz = np.random.randn(N).astype(np.float32)
    diff = np.random.randn(N).astype(np.float32)
    raw  = np.random.randn(N).astype(np.float32)

    feats = np.column_stack([cx, cy, cz, diff, raw])
    assert feats.shape == (N, 5), f"Expected (N,5), got {feats.shape}"

    # no_baseline mode: diff and raw both zeroed
    diff_nb = np.zeros(N, dtype=np.float32)
    raw_nb  = np.zeros(N, dtype=np.float32)
    feats_nb = np.column_stack([cx, cy, cz, diff_nb, raw_nb])
    assert feats_nb[:, 3].sum() == 0.0
    assert feats_nb[:, 4].sum() == 0.0

    # mask-only-diff: raw present, diff zeroed (partial-baseline mode)
    diff_mask = np.zeros(N, dtype=np.float32)
    feats_partial = np.column_stack([cx, cy, cz, diff_mask, raw])
    assert feats_partial[:, 3].sum() == 0.0
    assert feats_partial[:, 4].sum() != 0.0

    # healthy-node noise: only class-0 nodes are perturbed
    label_mock = np.zeros(N, dtype=np.int32)
    label_mock[:N//3] = 1   # first 1/3 are defective
    healthy_mask = (label_mock == 0).astype(np.float32)
    noise_h = np.random.normal(0, 0.03, N).astype(np.float32)
    raw_h   = raw + noise_h * healthy_mask
    # defective nodes should be unchanged
    assert np.allclose(raw_h[:N//3], raw[:N//3]), "defective nodes should not be perturbed"
    # healthy nodes should differ
    assert not np.allclose(raw_h[N//3:], raw[N//3:]), "healthy nodes should be perturbed"

    # baseline noise: diff is shifted by per-node perturbation
    bl_noise    = np.random.normal(0, 0.02, N).astype(np.float32)
    diff_bl     = diff - bl_noise
    assert not np.allclose(diff_bl, diff), "baseline noise should change diff channel"

    # channel dropout: diff is fully zeroed
    diff_dropped = np.zeros(N, dtype=np.float32)
    feats_drop   = np.column_stack([cx, cy, cz, diff_dropped, raw])
    assert feats_drop[:, 3].sum() == 0.0, "diff should be zero after dropout"
    assert feats_drop[:, 4].sum() != 0.0, "raw should still be present after dropout"

    print("[test] PASS — feature shapes and all augmentation modes correct.")

    # Verify in_channels=5 is accepted by T.build_model (if train.py is importable)
    try:
        model = T.build_model(arch="hybridmgn", in_channels=5)
        n_params = sum(p.numel() for p in model.parameters())
        # expect slightly more params than in_channels=4 version
        model4  = T.build_model(arch="hybridmgn", in_channels=4)
        n_params4 = sum(p.numel() for p in model4.parameters())
        assert n_params > n_params4, "5-channel model should have more params than 4-channel"
        print(f"[test] PASS — HybridMGN in_channels=5: {n_params:,} params "
              f"(vs 4-channel: {n_params4:,}, Δ={n_params - n_params4:,})")
    except Exception as e:
        print(f"[test] SKIP model build (Vancouver-only dep): {e}")

    print("[test] ALL PASS")


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

def _parse() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Dual-stream raw+diff GNN experiment")
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--train",       action="store_true")
    mode.add_argument("--eval",        action="store_true")
    mode.add_argument("--test",        action="store_true")

    ap.add_argument("--arch",         default="hybridmgn",
                    choices=["hybridmgn", "meshgraphnet", "gat", "sage"])
    ap.add_argument("--epochs",       type=int,   default=200)
    ap.add_argument("--batch_size",   type=int,   default=32)
    ap.add_argument("--lr",           type=float, default=1e-3)
    ap.add_argument("--eval_every",   type=int,   default=10)
    ap.add_argument("--noise_std",           type=float, default=0.05,
                    help="Noise on both channels of defective specimens")
    ap.add_argument("--noise_healthy_std",   type=float, default=0.03,
                    help="Extra noise on raw channel of healthy nodes (Stage-0 robustness)")
    ap.add_argument("--baseline_noise_std",  type=float, default=0.02,
                    help="Perturbation to diff channel simulating imperfect baseline")
    ap.add_argument("--diff_channel_dropout", type=float, default=0.15,
                    help="Prob of zeroing diff channel per specimen (no-baseline robustness)")
    ap.add_argument("--ckpt",                default=None,
                    help="Checkpoint path for --eval mode")
    ap.add_argument("--no_baseline",  action="store_true",
                    help="Zero the diff channel at eval (simulate no-baseline scenario)")
    return ap.parse_args()


if __name__ == "__main__":
    args = _parse()
    if args.test:
        _tests()
    elif args.train:
        train_dual(args)
    elif args.eval:
        if args.ckpt is None:
            args.ckpt = str(CK_OUT / f"{args.arch}_dual_best.pth")
        eval_dual(args)
