"""gen_inp.py -- generate COMPLETE, runnable Abaqus .inp decks (with real meshes)
for the CFRTP work, so they can be submitted directly:

    abaqus job=cfrtp_cure_residual        user=cfrtp_cure_umat.f  interactive
    abaqus job=cfrtp_delamination_mixedmode                       interactive

Two models:
  * cfrtp_cure_residual.inp        -- 3D [0/90] laminate residual stress via the
    CHILE cure UMAT (cfrtp_cure_umat.f), driven by a cure-cycle temperature field.
  * cfrtp_delamination_mixedmode.inp -- 2D plane-strain bilayer with a cohesive
    interface (built-in COH2D4 + Benzeggagh-Kenane), pre-crack, mixed-mode loading.

The meshes are generated explicitly here (no CAE needed). Still validate in Abaqus
(a 1-element free-contraction test for the UMAT first). This script only WRITES text;
it does not need Abaqus or numpy to run.
"""
from __future__ import annotations


# --------------------------------------------------------------------------- cure
def gen_cure(path, nx=6, ny=4, Lx=20.0e-3, Ly=12.0e-3, tply=0.6e-3):
    """3D [0/90] laminate: nx*ny in-plane cells, 2 plies through thickness (z)."""
    nz = 2                                        # one element per ply
    NX, NY, NZ = nx + 1, ny + 1, nz + 1
    xs = [Lx * i / nx for i in range(NX)]
    ys = [Ly * j / ny for j in range(NY)]
    zs = [tply * k for k in range(NZ)]            # 0, tply, 2*tply

    def nid(i, j, k):
        return 1 + (k * NY + j) * NX + i          # 1-based

    L = ["*HEADING",
         " CFRTP cure-induced residual stress (3D [0/90]) -- Abaqus/Standard",
         " CHILE cure UMAT (cfrtp_cure_umat.f). Generated by gen_inp.py.",
         "**"]
    L.append("*NODE, NSET=NALL")
    for k in range(NZ):
        for j in range(NY):
            for i in range(NX):
                L.append(f" {nid(i,j,k)}, {xs[i]:.6e}, {ys[j]:.6e}, {zs[k]:.6e}")

    # elements (C3D8), split into 0-deg (k=0) and 90-deg (k=1) ply element sets
    def eid(i, j, k):
        return 1 + (k * ny + j) * nx + i
    ely0, ely90 = [], []
    L.append("*ELEMENT, TYPE=C3D8, ELSET=EALL")
    for k in range(nz):
        for j in range(ny):
            for i in range(nx):
                n0 = nid(i, j, k); n1 = nid(i + 1, j, k); n2 = nid(i + 1, j + 1, k); n3 = nid(i, j + 1, k)
                m0 = nid(i, j, k + 1); m1 = nid(i + 1, j, k + 1); m2 = nid(i + 1, j + 1, k + 1); m3 = nid(i, j + 1, k + 1)
                e = eid(i, j, k)
                L.append(f" {e}, {n0}, {n1}, {n2}, {n3}, {m0}, {m1}, {m2}, {m3}")
                (ely0 if k == 0 else ely90).append(e)
    L.append("*ELSET, ELSET=PLY0")
    L.append(" " + ", ".join(str(e) for e in ely0))
    L.append("*ELSET, ELSET=PLY90")
    L.append(" " + ", ".join(str(e) for e in ely90))

    # orientations: 0 deg (fibre // x), 90 deg (fibre // y)
    L += ["**",
          "*ORIENTATION, NAME=ORI0, DEFINITION=COORDINATES",
          " 1.0, 0.0, 0.0,  0.0, 1.0, 0.0",
          " 3, 0.0",
          "*ORIENTATION, NAME=ORI90, DEFINITION=COORDINATES",
          " 0.0, 1.0, 0.0, -1.0, 0.0, 0.0",
          " 3, 0.0",
          "*SOLID SECTION, ELSET=PLY0,  MATERIAL=CFRTP, ORIENTATION=ORI0",
          "*SOLID SECTION, ELSET=PLY90, MATERIAL=CFRTP, ORIENTATION=ORI90"]

    # material: CHILE cure UMAT, 20 constants, 3 state vars
    L += ["**",
          "*MATERIAL, NAME=CFRTP",
          "*DEPVAR",
          " 3,",
          "1, alpha, degree of cure",
          "2, g_chile, stiffness fraction",
          "3, smax, max abs sigma11",
          "*USER MATERIAL, CONSTANTS=20",
          "** E1 E2 E3  NU12 NU13 NU23  G12 G13 G23  A1 A2 A3  BETA  AK EAK NEXP  AGEL G0 RGAS TABS",
          " 135.0e9, 9.0e9, 9.0e9, 0.30, 0.30, 0.45, 5.0e9, 5.0e9, 3.0e9,",
          " -0.3e-6, 28.0e-6, 28.0e-6, -3.0e-3,",
          " 1.0e8, 5.5e4, 1.6, 0.5, 0.02, 8.314, 273.15",
          "*INITIAL CONDITIONS, TYPE=TEMPERATURE",
          " NALL, 25.0",
          "*INITIAL CONDITIONS, TYPE=SOLUTION",
          " EALL, 0.0, 0.02, 0.0"]

    # 3-2-1 rigid-body suppression (free to contract & warp)
    nA = nid(0, 0, 0); nB = nid(nx, 0, 0); nC = nid(0, ny, 0)
    L += ["**",
          f"*NSET, NSET=NA\n {nA},",
          f"*NSET, NSET=NB\n {nB},",
          f"*NSET, NSET=NC\n {nC},",
          "*BOUNDARY",
          " NA, 1, 3, 0.0",
          " NB, 2, 2, 0.0",
          " NB, 3, 3, 0.0",
          " NC, 1, 1, 0.0",
          " NC, 3, 3, 0.0"]

    # cure cycle: heat 25->180, hold, cool -> 25 (total-time amplitude on [0,1])
    L += ["**",
          "*AMPLITUDE, NAME=CURECYCLE, TIME=TOTAL TIME",
          " 0.0, 25.0, 0.25, 180.0, 0.55, 180.0, 1.0, 25.0",
          "*STEP, NLGEOM=NO, INC=500",
          "*STATIC",
          " 0.005, 1.0, 1.0e-6, 0.02",
          "*TEMPERATURE, AMPLITUDE=CURECYCLE",
          " NALL, 1.0",
          "*OUTPUT, FIELD",
          "*ELEMENT OUTPUT",
          " S, E, SDV",
          "*NODE OUTPUT",
          " U",
          "*END STEP"]
    open(path, "w").write("\n".join(L) + "\n")
    return dict(nodes=NX * NY * NZ, els=nx * ny * nz)


# --------------------------------------------------------------- delamination (2D)
def gen_delam(path, nx=60, nzl=2, Lx=60.0e-3, t=0.6e-3, a0=15.0e-3, theta_deg=25.0):
    """2D plane-strain bilayer + cohesive interface (built-in COH2D4 + B-K).
    Bottom and top layers have SEPARATE interface nodes; cohesive elements join them."""
    import math
    NX = nx + 1
    xs = [Lx * i / nx for i in range(NX)]
    # bottom layer nodes: y in [0, t], rows 0..nzl ; top layer nodes: y in [t, 2t]
    NB = NX * (nzl + 1)

    def nb(i, j):                                 # bottom layer node (j=0..nzl)
        return 1 + j * NX + i

    def nt(i, j):                                 # top layer node (j=0..nzl)
        return 1 + NB + j * NX + i

    L = ["*HEADING",
         " CFRTP mixed-mode interlaminar delamination (2D plane strain)",
         " built-in cohesive (COH2D4) + Benzeggagh-Kenane. Generated by gen_inp.py.",
         "**", "*NODE, NSET=NALL"]
    for j in range(nzl + 1):
        for i in range(NX):
            L.append(f" {nb(i,j)}, {xs[i]:.6e}, {t*j/nzl:.6e}")
    for j in range(nzl + 1):
        for i in range(NX):
            L.append(f" {nt(i,j)}, {xs[i]:.6e}, {t + t*j/nzl:.6e}")

    # bulk elements (CPE4)
    def be(i, j):
        return 1 + j * nx + i

    def te(i, j):
        return 1000000 + 1 + j * nx + i
    L.append("*ELEMENT, TYPE=CPE4, ELSET=BOT")
    for j in range(nzl):
        for i in range(nx):
            L.append(f" {be(i,j)}, {nb(i,j)}, {nb(i+1,j)}, {nb(i+1,j+1)}, {nb(i,j+1)}")
    L.append("*ELEMENT, TYPE=CPE4, ELSET=TOP")
    for j in range(nzl):
        for i in range(nx):
            L.append(f" {te(i,j)}, {nt(i,j)}, {nt(i+1,j)}, {nt(i+1,j+1)}, {nt(i,j+1)}")

    # cohesive elements (COH2D4) between bottom top-row (j=nzl) and top bottom-row (j=0)
    # only in the bonded region x >= a0 (pre-crack ahead of the loaded end at x=0)
    L.append("*ELEMENT, TYPE=COH2D4, ELSET=COH")
    ce = 2000000
    for i in range(nx):
        if 0.5 * (xs[i] + xs[i + 1]) >= a0:
            ce += 1
            b0 = nb(i, nzl); b1 = nb(i + 1, nzl); t1 = nt(i + 1, 0); t0 = nt(i, 0)
            L.append(f" {ce}, {b0}, {b1}, {t1}, {t0}")

    # sections
    L += ["**",
          "*SOLID SECTION, ELSET=BOT, MATERIAL=PLY",
          "*SOLID SECTION, ELSET=TOP, MATERIAL=PLY",
          "*COHESIVE SECTION, ELSET=COH, MATERIAL=INTERFACE, RESPONSE=TRACTION SEPARATION, THICKNESS=SPECIFIED",
          " 1.0",
          "**",
          "*MATERIAL, NAME=PLY",
          "*ELASTIC",
          " 60.0e9, 0.30",
          "*MATERIAL, NAME=INTERFACE",
          "*ELASTIC, TYPE=TRACTION",
          " 1.0e14, 1.0e14, 1.0e14",
          "*DAMAGE INITIATION, CRITERION=QUADS",
          " 12.0e6, 18.0e6, 18.0e6",
          "*DAMAGE EVOLUTION, TYPE=ENERGY, MIXED MODE BEHAVIOR=BK, POWER=1.6",
          " 200.0, 600.0, 600.0",
          "*DAMAGE STABILIZATION",
          " 1.0e-5"]

    # BCs: clamp right end (x=Lx) of both layers; drive top-left tip (mixed mode)
    right_b = [nb(nx, j) for j in range(nzl + 1)]
    right_t = [nt(nx, j) for j in range(nzl + 1)]
    tip = nt(0, nzl)                              # top-arm upper-left corner
    L += ["**",
          "*NSET, NSET=CLAMP",
          " " + ", ".join(str(n) for n in right_b + right_t),
          f"*NSET, NSET=TIP\n {tip},",
          "*BOUNDARY",
          " CLAMP, 1, 2, 0.0"]
    th = math.radians(theta_deg)
    ux = 5.0e-4 * math.sin(th); uy = 5.0e-4 * math.cos(th)
    L += ["**",
          "*STEP, NLGEOM=YES, INC=1000",
          "*STATIC",
          " 0.002, 1.0, 1.0e-8, 0.02",
          "*BOUNDARY",
          f" TIP, 1, 1, {ux:.6e}",
          f" TIP, 2, 2, {uy:.6e}",
          "*CONTROLS, ANALYSIS=DISCONTINUOUS",
          "*OUTPUT, FIELD",
          "*ELEMENT OUTPUT, ELSET=COH",
          " SDEG, STATUS",
          "*NODE OUTPUT",
          " U, RF",
          "*END STEP"]
    open(path, "w").write("\n".join(L) + "\n")
    return dict(nodes=2 * NB, els=2 * nx * nzl, coh=ce - 2000000)


if __name__ == "__main__":
    import os
    here = os.path.dirname(os.path.abspath(__file__))
    c = gen_cure(os.path.join(here, "cfrtp_cure_residual.inp"))
    d = gen_delam(os.path.join(here, "cfrtp_delamination_mixedmode.inp"))
    print(f"cure  : {c['nodes']} nodes, {c['els']} C3D8 elements")
    print(f"delam : {d['nodes']} nodes, {d['els']} CPE4 + {d['coh']} COH2D4 elements")
