"""gen_inp.py -- generate COMPLETE, runnable Abaqus .inp decks (with real meshes)
for the CFRTP work, so they can be submitted directly:

    abaqus job=cfrtp_cure_residual        user=cfrtp_cure_umat.f  interactive
    abaqus job=cfrtp_delamination_mixedmode                       interactive

Two models:
  * cfrtp_cure_residual.inp        -- 3D [0/90] laminate residual stress via the
    CHILE cure UMAT (cfrtp_cure_umat.f), driven by a cure-cycle temperature field.
  * cfrtp_delamination_mixedmode.inp -- 2D plane-strain bilayer with a cohesive
    interface (built-in COH2D4 + Benzeggagh-Kenane), pre-crack, mixed-mode loading.

The meshes are generated explicitly here (no CAE needed). Still validate in Abaqus
(a 1-element free-contraction test for the UMAT first). This script only WRITES text;
it does not need Abaqus or numpy to run.
"""
from __future__ import annotations


# --------------------------------------------------------------------------- cure
def gen_cure(path, nx=6, ny=4, Lx=20.0e-3, Ly=12.0e-3, tply=0.6e-3):
    """3D [0/90] laminate: nx*ny in-plane cells, 2 plies through thickness (z)."""
    nz = 2                                        # one element per ply
    NX, NY, NZ = nx + 1, ny + 1, nz + 1
    xs = [Lx * i / nx for i in range(NX)]
    ys = [Ly * j / ny for j in range(NY)]
    zs = [tply * k for k in range(NZ)]            # 0, tply, 2*tply

    def nid(i, j, k):
        return 1 + (k * NY + j) * NX + i          # 1-based

    L = ["*HEADING",
         " CFRTP cure-induced residual stress (3D [0/90]) -- Abaqus/Standard",
         " CHILE cure UMAT (cfrtp_cure_umat.f). Generated by gen_inp.py.",
         "**"]
    L.append("*NODE, NSET=NALL")
    for k in range(NZ):
        for j in range(NY):
            for i in range(NX):
                L.append(f" {nid(i,j,k)}, {xs[i]:.6e}, {ys[j]:.6e}, {zs[k]:.6e}")

    # elements (C3D8), split into 0-deg (k=0) and 90-deg (k=1) ply element sets
    def eid(i, j, k):
        return 1 + (k * ny + j) * nx + i
    ely0, ely90 = [], []
    L.append("*ELEMENT, TYPE=C3D8, ELSET=EALL")
    for k in range(nz):
        for j in range(ny):
            for i in range(nx):
                n0 = nid(i, j, k); n1 = nid(i + 1, j, k); n2 = nid(i + 1, j + 1, k); n3 = nid(i, j + 1, k)
                m0 = nid(i, j, k + 1); m1 = nid(i + 1, j, k + 1); m2 = nid(i + 1, j + 1, k + 1); m3 = nid(i, j + 1, k + 1)
                e = eid(i, j, k)
                L.append(f" {e}, {n0}, {n1}, {n2}, {n3}, {m0}, {m1}, {m2}, {m3}")
                (ely0 if k == 0 else ely90).append(e)
    # NB: Abaqus allows at most 16 items per data line, so use GENERATE
    # (first, last, increment) for these contiguous element ranges.
    L.append("*ELSET, ELSET=PLY0, GENERATE")
    L.append(f" {ely0[0]}, {ely0[-1]}, 1")
    L.append("*ELSET, ELSET=PLY90, GENERATE")
    L.append(f" {ely90[0]}, {ely90[-1]}, 1")

    # orientations: 0 deg (fibre // x), 90 deg (fibre // y)
    L += ["**",
          "*ORIENTATION, NAME=ORI0, DEFINITION=COORDINATES",
          " 1.0, 0.0, 0.0,  0.0, 1.0, 0.0",
          " 3, 0.0",
          "*ORIENTATION, NAME=ORI90, DEFINITION=COORDINATES",
          " 0.0, 1.0, 0.0, -1.0, 0.0, 0.0",
          " 3, 0.0",
          "*SOLID SECTION, ELSET=PLY0,  MATERIAL=CFRTP, ORIENTATION=ORI0",
          "*SOLID SECTION, ELSET=PLY90, MATERIAL=CFRTP, ORIENTATION=ORI90"]

    # material: CHILE cure UMAT, 20 constants, 3 state vars
    L += ["**",
          "*MATERIAL, NAME=CFRTP",
          "*DEPVAR",
          " 3,",
          "1, alpha, degree of cure",
          "2, g_chile, stiffness fraction",
          "3, smax, max abs sigma11",
          "*USER MATERIAL, CONSTANTS=20",
          "** Abaqus *USER MATERIAL allows at most 8 values per data line --",
          "** exceeding it silently drops values and shifts everything after,",
          "** so each line below is packed to <=8 (E1..G13 / G23..NEXP / AGEL..TABS).",
          "** E1 E2 E3  NU12 NU13 NU23  G12 G13",
          " 135.0e9, 9.0e9, 9.0e9, 0.30, 0.30, 0.45, 5.0e9, 5.0e9,",
          "** G23  A1 A2 A3  BETA  AK EAK NEXP",
          " 3.0e9, -0.3e-6, 28.0e-6, 28.0e-6, -3.0e-3, 1.0e8, 5.5e4, 1.6,",
          "** AGEL G0 RGAS TABS",
          " 0.5, 0.02, 8.314, 273.15",
          "*INITIAL CONDITIONS, TYPE=TEMPERATURE",
          " NALL, 25.0",
          "*INITIAL CONDITIONS, TYPE=SOLUTION",
          " EALL, 0.0, 0.02, 0.0"]

    # 3-2-1 rigid-body suppression (free to contract & warp)
    nA = nid(0, 0, 0); nB = nid(nx, 0, 0); nC = nid(0, ny, 0)
    L += ["**",
          f"*NSET, NSET=NA\n {nA},",
          f"*NSET, NSET=NB\n {nB},",
          f"*NSET, NSET=NC\n {nC},",
          "*BOUNDARY",
          " NA, 1, 3, 0.0",
          " NB, 2, 2, 0.0",
          " NB, 3, 3, 0.0",
          " NC, 1, 1, 0.0",
          " NC, 3, 3, 0.0"]

    # cure cycle: heat 25->180, hold, cool -> 25 (total-time amplitude on [0,1])
    L += ["**",
          "*AMPLITUDE, NAME=CURECYCLE, TIME=TOTAL TIME",
          " 0.0, 25.0, 0.25, 180.0, 0.55, 180.0, 1.0, 25.0",
          "*STEP, NLGEOM=NO, INC=500",
          "*STATIC",
          " 0.005, 1.0, 1.0e-6, 0.02",
          "*TEMPERATURE, AMPLITUDE=CURECYCLE",
          " NALL, 1.0",
          "*OUTPUT, FIELD",
          "*ELEMENT OUTPUT",
          " S, E, SDV",
          "*NODE OUTPUT",
          " U",
          "*END STEP"]
    open(path, "w").write("\n".join(L) + "\n")
    return dict(nodes=NX * NY * NZ, els=nx * ny * nz)


# ------------------------------------------------------- 1-element free-contraction
def gen_1elem_sanity(path, L=0.6e-3):
    """Single C3D8, ORI0 ply, 3-2-1 statically-determinate support (free to
    contract), same material + cure cycle as gen_cure. A single homogeneous
    ply with no external constraint beyond rigid-body suppression must end
    at ~0 residual stress -- if not, the UMAT eigenstrain sign/ordering or
    the BC set is wrong."""
    # explicit unit-cube node numbering (matches gen_cure's C3D8 connectivity order)
    coords = {
        1: (0.0, 0.0, 0.0), 2: (L, 0.0, 0.0), 3: (L, L, 0.0), 4: (0.0, L, 0.0),
        5: (0.0, 0.0, L),   6: (L, 0.0, L),   7: (L, L, L),   8: (0.0, L, L),
    }
    L_ = ["*HEADING",
          " CFRTP UMAT 1-element free-contraction sanity test -- Abaqus/Standard",
          " Single ply, 3-2-1 support, same cure cycle as cfrtp_cure_residual.inp.",
          " Expect residual sigma ~ 0 at every increment (nothing external restrains it).",
          "**",
          "*NODE, NSET=NALL"]
    for n, (x, y, z) in coords.items():
        L_.append(f" {n}, {x:.6e}, {y:.6e}, {z:.6e}")
    L_ += ["*ELEMENT, TYPE=C3D8, ELSET=EALL",
           " 1, 1, 2, 3, 4, 5, 6, 7, 8",
           "**",
           "*ORIENTATION, NAME=ORI0, DEFINITION=COORDINATES",
           " 1.0, 0.0, 0.0,  0.0, 1.0, 0.0",
           " 3, 0.0",
           "*SOLID SECTION, ELSET=EALL, MATERIAL=CFRTP, ORIENTATION=ORI0",
           "**",
           "*MATERIAL, NAME=CFRTP",
           "*DEPVAR",
           " 3,",
           "1, alpha, degree of cure",
           "2, g_chile, stiffness fraction",
           "3, smax, max abs sigma11",
           "*USER MATERIAL, CONSTANTS=20",
           " 135.0e9, 9.0e9, 9.0e9, 0.30, 0.30, 0.45, 5.0e9, 5.0e9,",
           " 3.0e9, -0.3e-6, 28.0e-6, 28.0e-6, -3.0e-3, 1.0e8, 5.5e4, 1.6,",
           " 0.5, 0.02, 8.314, 273.15",
           "*INITIAL CONDITIONS, TYPE=TEMPERATURE",
           " NALL, 25.0",
           "*INITIAL CONDITIONS, TYPE=SOLUTION",
           " EALL, 0.0, 0.02, 0.0"]
    # 3-2-1: node 1 all three, node 2 (along x from node1) y&z, node 4 (along y) z only
    L_ += ["**",
           "*NSET, NSET=NA\n 1,",
           "*NSET, NSET=NB\n 2,",
           "*NSET, NSET=NC\n 4,",
           "*BOUNDARY",
           " NA, 1, 3, 0.0",
           " NB, 2, 2, 0.0",
           " NB, 3, 3, 0.0",
           " NC, 1, 1, 0.0",
           " NC, 3, 3, 0.0"]
    L_ += ["**",
           "*AMPLITUDE, NAME=CURECYCLE, TIME=TOTAL TIME",
           " 0.0, 25.0, 0.25, 180.0, 0.55, 180.0, 1.0, 25.0",
           "*STEP, NLGEOM=NO, INC=500",
           "*STATIC",
           " 0.005, 1.0, 1.0e-6, 0.02",
           "*TEMPERATURE, AMPLITUDE=CURECYCLE",
           " NALL, 1.0",
           "*OUTPUT, FIELD",
           "*ELEMENT OUTPUT",
           " S, E, SDV",
           "*NODE OUTPUT",
           " U",
           "*END STEP"]
    open(path, "w").write("\n".join(L_) + "\n")
    return dict(nodes=8, els=1)


# ------------------------------------------------- cure residual, viscoelastic UMAT
def gen_cure_ve(path, nx=6, ny=4, Lx=20.0e-3, Ly=12.0e-3, tply=0.6e-3):
    """Same [0/90] mesh as gen_cure, but driven by the thermo-VISCOELASTIC
    UMAT (cfrtp_cure_umat_ve.f): generalized-Maxwell relaxation + WLF shift.
    Reproduces the elastic->viscoelastic stress drop of the Python demo
    cfrtp_viscoelastic_residual_stress.py inside Abaqus.

    NB: Prony tau_k are in the SAME time unit as the step (total time 1.0
    here), so relaxation is visible within the normalized cure cycle; rescale
    tau_k (and re-tune the kinetics AK) to seconds for a physical run."""
    nz = 2
    NX, NY, NZ = nx + 1, ny + 1, nz + 1
    xs = [Lx * i / nx for i in range(NX)]
    ys = [Ly * j / ny for j in range(NY)]
    zs = [tply * k for k in range(NZ)]

    def nid(i, j, k):
        return 1 + (k * NY + j) * NX + i

    def eid(i, j, k):
        return 1 + (k * ny + j) * nx + i

    L = ["*HEADING",
         " CFRTP cure residual stress (3D [0/90]) -- THERMO-VISCOELASTIC UMAT",
         " CHILE + generalized-Maxwell (Prony) + WLF. cfrtp_cure_umat_ve.f.",
         "**", "*NODE, NSET=NALL"]
    for k in range(NZ):
        for j in range(NY):
            for i in range(NX):
                L.append(f" {nid(i,j,k)}, {xs[i]:.6e}, {ys[j]:.6e}, {zs[k]:.6e}")

    ely0, ely90 = [], []
    L.append("*ELEMENT, TYPE=C3D8, ELSET=EALL")
    for k in range(nz):
        for j in range(ny):
            for i in range(nx):
                n0 = nid(i, j, k); n1 = nid(i + 1, j, k); n2 = nid(i + 1, j + 1, k); n3 = nid(i, j + 1, k)
                m0 = nid(i, j, k + 1); m1 = nid(i + 1, j, k + 1); m2 = nid(i + 1, j + 1, k + 1); m3 = nid(i, j + 1, k + 1)
                e = eid(i, j, k)
                L.append(f" {e}, {n0}, {n1}, {n2}, {n3}, {m0}, {m1}, {m2}, {m3}")
                (ely0 if k == 0 else ely90).append(e)
    L.append("*ELSET, ELSET=PLY0, GENERATE")
    L.append(f" {ely0[0]}, {ely0[-1]}, 1")
    L.append("*ELSET, ELSET=PLY90, GENERATE")
    L.append(f" {ely90[0]}, {ely90[-1]}, 1")

    L += ["**",
          "*ORIENTATION, NAME=ORI0, DEFINITION=COORDINATES",
          " 1.0, 0.0, 0.0,  0.0, 1.0, 0.0",
          " 3, 0.0",
          "*ORIENTATION, NAME=ORI90, DEFINITION=COORDINATES",
          " 0.0, 1.0, 0.0, -1.0, 0.0, 0.0",
          " 3, 0.0",
          "*SOLID SECTION, ELSET=PLY0,  MATERIAL=CFRTPVE, ORIENTATION=ORI0",
          "*SOLID SECTION, ELSET=PLY90, MATERIAL=CFRTPVE, ORIENTATION=ORI90"]

    # material: viscoelastic CHILE UMAT, 30 constants, 22 state vars.
    # *USER MATERIAL data lines are capped at 8 values/line -> pack 8/8/8/6.
    L += ["**",
          "*MATERIAL, NAME=CFRTPVE",
          "*DEPVAR",
          " 22,",
          "1, alpha, degree of cure",
          "2, g_chile, stiffness fraction",
          "3, smax, max abs sigma11",
          "4, aT, WLF shift factor",
          "*USER MATERIAL, CONSTANTS=30",
          "** E1 E2 E3  NU12 NU13 NU23  G12 G13",
          " 135.0e9, 9.0e9, 9.0e9, 0.30, 0.30, 0.45, 5.0e9, 5.0e9,",
          "** G23  A1 A2 A3  BETA  AK EAK NEXP",
          " 3.0e9, -0.3e-6, 28.0e-6, 28.0e-6, -3.0e-3, 1.0e8, 5.5e4, 1.6,",
          "** AGEL G0 RGAS TABS  GINF  G1 TAU1 G2   (ginf+g1+g2+g3 = 1)",
          " 0.5, 0.02, 8.314, 273.15, 0.3, 0.4, 0.02, 0.2,",
          "** TAU2 G3 TAU3  WLF_C1 WLF_C2 WLF_TREF(C)",
          " 0.1, 0.1, 0.5, 20.0, 80.0, 100.0",
          "*INITIAL CONDITIONS, TYPE=TEMPERATURE",
          " NALL, 25.0"]

    nA = nid(0, 0, 0); nB = nid(nx, 0, 0); nC = nid(0, ny, 0)
    L += ["**",
          f"*NSET, NSET=NA\n {nA},",
          f"*NSET, NSET=NB\n {nB},",
          f"*NSET, NSET=NC\n {nC},",
          "*BOUNDARY",
          " NA, 1, 3, 0.0",
          " NB, 2, 2, 0.0",
          " NB, 3, 3, 0.0",
          " NC, 1, 1, 0.0",
          " NC, 3, 3, 0.0"]

    L += ["**",
          "*AMPLITUDE, NAME=CURECYCLE, TIME=TOTAL TIME",
          " 0.0, 25.0, 0.25, 180.0, 0.55, 180.0, 1.0, 25.0",
          "*STEP, NLGEOM=NO, INC=500",
          "*STATIC",
          " 0.005, 1.0, 1.0e-6, 0.02",
          "*TEMPERATURE, AMPLITUDE=CURECYCLE",
          " NALL, 1.0",
          "*OUTPUT, FIELD",
          "*ELEMENT OUTPUT",
          " S, E, SDV",
          "*NODE OUTPUT",
          " U",
          "*END STEP"]
    open(path, "w").write("\n".join(L) + "\n")
    return dict(nodes=NX * NY * NZ, els=nx * ny * nz)


# ---------------------------------------- cure residual, crystallization + VE UMAT
def gen_cryst_ve(path, nx=6, ny=4, Lx=20.0e-3, Ly=12.0e-3, tply=0.6e-3):
    """Same [0/90] mesh, driven by the CRYSTALLIZATION-COUPLED viscoelastic UMAT
    (cfrtp_cryst_umat_ve.f): alpha = relative crystallinity from a Nakamura
    non-isothermal law, developed on a MELT -> COOL cycle, controlling stiffness,
    crystallization shrinkage and the relaxation shift. Reproduces the
    cooling-rate -> crystallinity -> residual-stress pathway for semi-crystalline
    fluoropolymer CFRTP. Prony tau_k in the step's (normalized) time unit --
    co-calibrate with the real cool-down duration + DMA before trusting values."""
    nz = 2
    NX, NY, NZ = nx + 1, ny + 1, nz + 1
    xs = [Lx * i / nx for i in range(NX)]
    ys = [Ly * j / ny for j in range(NY)]
    zs = [tply * k for k in range(NZ)]

    def nid(i, j, k):
        return 1 + (k * NY + j) * NX + i

    def eid(i, j, k):
        return 1 + (k * ny + j) * nx + i

    L = ["*HEADING",
         " CFRTP residual stress (3D [0/90]) -- CRYSTALLIZATION-COUPLED VE UMAT",
         " Nakamura crystallization + Prony/WLF + crystallinity shift. "
         "cfrtp_cryst_umat_ve.f.",
         "**", "*NODE, NSET=NALL"]
    for k in range(NZ):
        for j in range(NY):
            for i in range(NX):
                L.append(f" {nid(i,j,k)}, {xs[i]:.6e}, {ys[j]:.6e}, {zs[k]:.6e}")

    ely0, ely90 = [], []
    L.append("*ELEMENT, TYPE=C3D8, ELSET=EALL")
    for k in range(nz):
        for j in range(ny):
            for i in range(nx):
                n0 = nid(i, j, k); n1 = nid(i + 1, j, k); n2 = nid(i + 1, j + 1, k); n3 = nid(i, j + 1, k)
                m0 = nid(i, j, k + 1); m1 = nid(i + 1, j, k + 1); m2 = nid(i + 1, j + 1, k + 1); m3 = nid(i, j + 1, k + 1)
                e = eid(i, j, k)
                L.append(f" {e}, {n0}, {n1}, {n2}, {n3}, {m0}, {m1}, {m2}, {m3}")
                (ely0 if k == 0 else ely90).append(e)
    L.append("*ELSET, ELSET=PLY0, GENERATE")
    L.append(f" {ely0[0]}, {ely0[-1]}, 1")
    L.append("*ELSET, ELSET=PLY90, GENERATE")
    L.append(f" {ely90[0]}, {ely90[-1]}, 1")

    L += ["**",
          "*ORIENTATION, NAME=ORI0, DEFINITION=COORDINATES",
          " 1.0, 0.0, 0.0,  0.0, 1.0, 0.0",
          " 3, 0.0",
          "*ORIENTATION, NAME=ORI90, DEFINITION=COORDINATES",
          " 0.0, 1.0, 0.0, -1.0, 0.0, 0.0",
          " 3, 0.0",
          "*SOLID SECTION, ELSET=PLY0,  MATERIAL=CFRTPX, ORIENTATION=ORI0",
          "*SOLID SECTION, ELSET=PLY90, MATERIAL=CFRTPX, ORIENTATION=ORI90"]

    # crystallization-coupled viscoelastic UMAT: 30 constants, 23 state vars.
    # *USER MATERIAL data lines capped at 8 values/line -> pack 8/8/8/6.
    L += ["**",
          "*MATERIAL, NAME=CFRTPX",
          "*DEPVAR",
          " 23,",
          "1, alpha, relative crystallinity",
          "2, g_chile, stiffness fraction",
          "3, smax, max abs sigma11",
          "4, aT, WLF shift",
          "5, aX, crystallinity shift",
          "*USER MATERIAL, CONSTANTS=30",
          "** E1 E2 E3  NU12 NU13 NU23  G12 G13",
          " 135.0e9, 9.0e9, 9.0e9, 0.30, 0.30, 0.45, 5.0e9, 5.0e9,",
          "** G23  A1 A2 A3  BETA  NAVRAMI KMAX TCRYST",
          " 3.0e9, -0.3e-6, 28.0e-6, 28.0e-6, -3.0e-3, 2.5, 3.0, 120.0,",
          "** WCRYST AGEL G0  GINF  G1 TAU1 G2 TAU2   (ginf+g1+g2+g3 = 1)",
          " 30.0, 0.2, 0.02, 0.3, 0.4, 0.02, 0.2, 0.1,",
          "** G3 TAU3  WLF_C1 WLF_C2 WLF_TREF(C)  BX",
          " 0.1, 0.5, 20.0, 80.0, 140.0, 2.0",
          "*INITIAL CONDITIONS, TYPE=TEMPERATURE",
          " NALL, 260.0",
          "*INITIAL CONDITIONS, TYPE=SOLUTION",
          " EALL, 1.0e-3"]

    nA = nid(0, 0, 0); nB = nid(nx, 0, 0); nC = nid(0, ny, 0)
    L += ["**",
          f"*NSET, NSET=NA\n {nA},",
          f"*NSET, NSET=NB\n {nB},",
          f"*NSET, NSET=NC\n {nC},",
          "*BOUNDARY",
          " NA, 1, 3, 0.0",
          " NB, 2, 2, 0.0",
          " NB, 3, 3, 0.0",
          " NC, 1, 1, 0.0",
          " NC, 3, 3, 0.0"]

    # melt -> hold -> cool cycle (total-time amplitude on [0,1]); crystallizes on
    # cooling through the TCRYST window.
    L += ["**",
          "*AMPLITUDE, NAME=MELTCOOL, TIME=TOTAL TIME",
          " 0.0, 260.0, 0.15, 260.0, 1.0, 25.0",
          "*STEP, NLGEOM=NO, INC=500",
          "*STATIC",
          " 0.005, 1.0, 1.0e-6, 0.02",
          "*TEMPERATURE, AMPLITUDE=MELTCOOL",
          " NALL, 1.0",
          "*OUTPUT, FIELD",
          "*ELEMENT OUTPUT",
          " S, E, SDV",
          "*NODE OUTPUT",
          " U",
          "*END STEP"]
    open(path, "w").write("\n".join(L) + "\n")
    return dict(nodes=NX * NY * NZ, els=nx * ny * nz)


# ------------------------------------------- PEEK/carbon crystallization VALIDATION
def gen_cryst_peek(path, nx=6, ny=4, Lx=20.0e-3, Ly=12.0e-3, tply=0.6e-3):
    """VALIDATION benchmark for the crystallization-coupled VE UMAT, using
    literature-typical AS4/PEEK (APC-2) values -- because public crystallization +
    residual-stress data exist for carbon/PEEK (fluoropolymer-CF data are
    proprietary). Run this to confirm the METHOD reproduces the known
    cooling-rate -> crystallinity -> residual-stress behaviour, then swap in the
    Daikin system once data are available.

    Property provenance (LITERATURE-TYPICAL -- confirm against the cited sources,
    NOT extracted from a single table):
      - AS4/PEEK elastic constants: standard APC-2 lamina values.
      - PEEK crystallization: Avrami/Nakamura n ~ 2.5; bell-shaped K(T) centred in
        the PEEK crystallization window (Tg~143, Tm~343 C). KMAX calibrated by
        simulation so alpha -> ~1 over this deck's cool-down (dt-converged).
      - WLF: universal constants C1=17.4, C2=51.6 at Tref=Tg=143 C.
      Refs: Parlevliet et al., Composites Part A (2006-07); Tierney & Gillespie,
      Composites Part A (2004); MDPI Polymers PEEK crystallization (2025)."""
    nz = 2
    NX, NY, NZ = nx + 1, ny + 1, nz + 1
    xs = [Lx * i / nx for i in range(NX)]
    ys = [Ly * j / ny for j in range(NY)]
    zs = [tply * k for k in range(NZ)]

    def nid(i, j, k):
        return 1 + (k * NY + j) * NX + i

    def eid(i, j, k):
        return 1 + (k * ny + j) * nx + i

    L = ["*HEADING",
         " Carbon/PEEK crystallization-coupled residual stress -- VALIDATION case",
         " Nakamura + Prony/WLF (AS4/PEEK literature-typical). cfrtp_cryst_umat_ve.f.",
         "**", "*NODE, NSET=NALL"]
    for k in range(NZ):
        for j in range(NY):
            for i in range(NX):
                L.append(f" {nid(i,j,k)}, {xs[i]:.6e}, {ys[j]:.6e}, {zs[k]:.6e}")

    ely0, ely90 = [], []
    L.append("*ELEMENT, TYPE=C3D8, ELSET=EALL")
    for k in range(nz):
        for j in range(ny):
            for i in range(nx):
                n0 = nid(i, j, k); n1 = nid(i + 1, j, k); n2 = nid(i + 1, j + 1, k); n3 = nid(i, j + 1, k)
                m0 = nid(i, j, k + 1); m1 = nid(i + 1, j, k + 1); m2 = nid(i + 1, j + 1, k + 1); m3 = nid(i, j + 1, k + 1)
                e = eid(i, j, k)
                L.append(f" {e}, {n0}, {n1}, {n2}, {n3}, {m0}, {m1}, {m2}, {m3}")
                (ely0 if k == 0 else ely90).append(e)
    L.append("*ELSET, ELSET=PLY0, GENERATE")
    L.append(f" {ely0[0]}, {ely0[-1]}, 1")
    L.append("*ELSET, ELSET=PLY90, GENERATE")
    L.append(f" {ely90[0]}, {ely90[-1]}, 1")

    L += ["**",
          "*ORIENTATION, NAME=ORI0, DEFINITION=COORDINATES",
          " 1.0, 0.0, 0.0,  0.0, 1.0, 0.0",
          " 3, 0.0",
          "*ORIENTATION, NAME=ORI90, DEFINITION=COORDINATES",
          " 0.0, 1.0, 0.0, -1.0, 0.0, 0.0",
          " 3, 0.0",
          "*SOLID SECTION, ELSET=PLY0,  MATERIAL=PEEKCF, ORIENTATION=ORI0",
          "*SOLID SECTION, ELSET=PLY90, MATERIAL=PEEKCF, ORIENTATION=ORI90"]

    # AS4/PEEK crystallization-coupled VE UMAT: 30 constants, 23 state vars.
    # *USER MATERIAL data lines capped at 8 values/line -> pack 8/8/8/6.
    L += ["**",
          "*MATERIAL, NAME=PEEKCF",
          "*DEPVAR",
          " 23,",
          "1, alpha, relative crystallinity",
          "2, g_chile, stiffness fraction",
          "3, smax, max abs sigma11",
          "4, aT, WLF shift",
          "5, aX, crystallinity shift",
          "*USER MATERIAL, CONSTANTS=30",
          "** E1 E2 E3  NU12 NU13 NU23  G12 G13   (AS4/PEEK APC-2)",
          " 138.0e9, 10.2e9, 10.2e9, 0.30, 0.30, 0.45, 5.7e9, 5.7e9,",
          "** G23  A1 A2 A3  BETA  NAVRAMI KMAX TCRYST",
          " 3.5e9, -0.2e-6, 30.0e-6, 30.0e-6, -4.0e-3, 2.5, 12.0, 290.0,",
          "** WCRYST AGEL G0  GINF  G1 TAU1 G2 TAU2   (ginf+g1+g2+g3 = 1)",
          " 45.0, 0.1, 0.01, 0.3, 0.4, 0.02, 0.2, 0.1,",
          "** G3 TAU3  WLF_C1 WLF_C2 WLF_TREF(Tg,C)  BX",
          " 0.1, 0.5, 17.4, 51.6, 143.0, 2.0",
          "*INITIAL CONDITIONS, TYPE=TEMPERATURE",
          " NALL, 380.0",
          "*INITIAL CONDITIONS, TYPE=SOLUTION",
          " EALL, 1.0e-3"]

    nA = nid(0, 0, 0); nB = nid(nx, 0, 0); nC = nid(0, ny, 0)
    L += ["**",
          f"*NSET, NSET=NA\n {nA},",
          f"*NSET, NSET=NB\n {nB},",
          f"*NSET, NSET=NC\n {nC},",
          "*BOUNDARY",
          " NA, 1, 3, 0.0",
          " NB, 2, 2, 0.0",
          " NB, 3, 3, 0.0",
          " NC, 1, 1, 0.0",
          " NC, 3, 3, 0.0"]

    # melt (above Tm=343) -> hold -> cool to RT; crystallizes on cooling through the
    # ~230-335 C window (TCRYST=290). Total-time amplitude on [0,1].
    L += ["**",
          "*AMPLITUDE, NAME=MELTCOOL, TIME=TOTAL TIME",
          " 0.0, 380.0, 0.15, 380.0, 1.0, 25.0",
          "*STEP, NLGEOM=NO, INC=500",
          "*STATIC",
          " 0.005, 1.0, 1.0e-6, 0.02",
          "*TEMPERATURE, AMPLITUDE=MELTCOOL",
          " NALL, 1.0",
          "*OUTPUT, FIELD",
          "*ELEMENT OUTPUT",
          " S, E, SDV",
          "*NODE OUTPUT",
          " U",
          "*END STEP"]
    open(path, "w").write("\n".join(L) + "\n")
    return dict(nodes=NX * NY * NZ, els=nx * ny * nz)


# --------------------------------------------------------------- delamination (2D)
def gen_delam(path, nx=60, nzl=2, Lx=60.0e-3, t=0.6e-3, a0=15.0e-3, theta_deg=25.0):
    """2D plane-strain bilayer + cohesive interface (built-in COH2D4 + B-K).
    Bottom and top layers have SEPARATE interface nodes; cohesive elements join them."""
    import math
    NX = nx + 1
    xs = [Lx * i / nx for i in range(NX)]
    # bottom layer nodes: y in [0, t], rows 0..nzl ; top layer nodes: y in [t, 2t]
    NB = NX * (nzl + 1)

    def nb(i, j):                                 # bottom layer node (j=0..nzl)
        return 1 + j * NX + i

    def nt(i, j):                                 # top layer node (j=0..nzl)
        return 1 + NB + j * NX + i

    L = ["*HEADING",
         " CFRTP mixed-mode interlaminar delamination (2D plane strain)",
         " built-in cohesive (COH2D4) + Benzeggagh-Kenane. Generated by gen_inp.py.",
         "**", "*NODE, NSET=NALL"]
    for j in range(nzl + 1):
        for i in range(NX):
            L.append(f" {nb(i,j)}, {xs[i]:.6e}, {t*j/nzl:.6e}")
    for j in range(nzl + 1):
        for i in range(NX):
            L.append(f" {nt(i,j)}, {xs[i]:.6e}, {t + t*j/nzl:.6e}")

    # bulk elements (CPE4)
    def be(i, j):
        return 1 + j * nx + i

    def te(i, j):
        return 1000000 + 1 + j * nx + i
    L.append("*ELEMENT, TYPE=CPE4, ELSET=BOT")
    for j in range(nzl):
        for i in range(nx):
            L.append(f" {be(i,j)}, {nb(i,j)}, {nb(i+1,j)}, {nb(i+1,j+1)}, {nb(i,j+1)}")
    L.append("*ELEMENT, TYPE=CPE4, ELSET=TOP")
    for j in range(nzl):
        for i in range(nx):
            L.append(f" {te(i,j)}, {nt(i,j)}, {nt(i+1,j)}, {nt(i+1,j+1)}, {nt(i,j+1)}")

    # cohesive elements (COH2D4) between bottom top-row (j=nzl) and top bottom-row (j=0)
    # only in the bonded region x >= a0 (pre-crack ahead of the loaded end at x=0)
    L.append("*ELEMENT, TYPE=COH2D4, ELSET=COH")
    ce = 2000000
    for i in range(nx):
        if 0.5 * (xs[i] + xs[i + 1]) >= a0:
            ce += 1
            b0 = nb(i, nzl); b1 = nb(i + 1, nzl); t1 = nt(i + 1, 0); t0 = nt(i, 0)
            L.append(f" {ce}, {b0}, {b1}, {t1}, {t0}")

    # sections
    L += ["**",
          "*SOLID SECTION, ELSET=BOT, MATERIAL=PLY",
          "*SOLID SECTION, ELSET=TOP, MATERIAL=PLY",
          "*SECTION CONTROLS, NAME=COHVISC, VISCOSITY=1.0e-5",
          "*COHESIVE SECTION, ELSET=COH, MATERIAL=INTERFACE, RESPONSE=TRACTION SEPARATION,"
          " THICKNESS=SPECIFIED, CONTROLS=COHVISC",
          " 1.0",
          "**",
          "*MATERIAL, NAME=PLY",
          "*ELASTIC",
          " 60.0e9, 0.30",
          "*MATERIAL, NAME=INTERFACE",
          "*ELASTIC, TYPE=TRACTION",
          " 1.0e14, 1.0e14, 1.0e14",
          "*DAMAGE INITIATION, CRITERION=QUADS",
          " 12.0e6, 18.0e6, 18.0e6",
          "*DAMAGE EVOLUTION, TYPE=ENERGY, MIXED MODE BEHAVIOR=BK, POWER=1.6",
          " 200.0, 600.0, 600.0"]

    # BCs: clamp right end (x=Lx) of both layers; drive top-left tip (mixed mode)
    right_b = [nb(nx, j) for j in range(nzl + 1)]
    right_t = [nt(nx, j) for j in range(nzl + 1)]
    tip = nt(0, nzl)                              # top-arm upper-left corner
    L += ["**",
          "*NSET, NSET=CLAMP",
          " " + ", ".join(str(n) for n in right_b + right_t),
          f"*NSET, NSET=TIP\n {tip},",
          "*BOUNDARY",
          " CLAMP, 1, 2, 0.0"]
    th = math.radians(theta_deg)
    ux = 5.0e-4 * math.sin(th); uy = 5.0e-4 * math.cos(th)
    L += ["**",
          "*STEP, NLGEOM=YES, INC=1000",
          "*STATIC",
          " 0.002, 1.0, 1.0e-8, 0.02",
          "*BOUNDARY",
          f" TIP, 1, 1, {ux:.6e}",
          f" TIP, 2, 2, {uy:.6e}",
          "*CONTROLS, ANALYSIS=DISCONTINUOUS",
          "*OUTPUT, FIELD",
          "*ELEMENT OUTPUT, ELSET=COH",
          " SDEG, STATUS",
          "*NODE OUTPUT",
          " U, RF",
          "*END STEP"]
    open(path, "w").write("\n".join(L) + "\n")
    return dict(nodes=2 * NB, els=2 * nx * nzl, coh=ce - 2000000)


# ------------------------------------------------------------- delamination (3D)
def gen_delam3d(path, nx=40, ny=3, Lx=60.0e-3, Ly=20.0e-3, t=0.6e-3,
                a0=15.0e-3, theta_deg=30.0):
    """3D mixed-mode interlaminar delamination: two solid sublaminates (C3D8)
    joined by a cohesive layer (COH3D8) with Benzeggagh-Kenane mixed mode.
    Separate interface nodes on each sublaminate; cohesive elements only in the
    bonded region x >= a0 (pre-crack ahead of the loaded near end x=0). The 3D
    counterpart of gen_delam / cfrtp_delamination_2d_fe.py -- lets a curved
    delamination FRONT develop across the width y."""
    import math
    NX, NY = nx + 1, ny + 1
    xs = [Lx * i / nx for i in range(NX)]
    ysg = [Ly * j / ny for j in range(NY)]
    NB = NX * NY * 2                              # nodes in the bottom sublaminate

    def nb(i, j, k):                             # bottom sublaminate (z=0..t)
        return 1 + (k * NY + j) * NX + i

    def nt(i, j, k):                             # top sublaminate (z=t..2t)
        return 1 + NB + (k * NY + j) * NX + i

    L = ["*HEADING",
         " CFRTP 3D mixed-mode interlaminar delamination (COH3D8 + B-K)",
         " Two C3D8 sublaminates + cohesive layer. Generated by gen_inp.py.",
         "**", "*NODE, NSET=NALL"]
    for k in range(2):
        for j in range(NY):
            for i in range(NX):
                L.append(f" {nb(i,j,k)}, {xs[i]:.6e}, {ysg[j]:.6e}, {t*k:.6e}")
    for k in range(2):
        for j in range(NY):
            for i in range(NX):
                L.append(f" {nt(i,j,k)}, {xs[i]:.6e}, {ysg[j]:.6e}, {t+t*k:.6e}")

    def hexc(nfun, i, j):                        # C3D8 connectivity (z0 face, z1 face)
        return (f" {nfun(i,j,0)}, {nfun(i+1,j,0)}, {nfun(i+1,j+1,0)}, {nfun(i,j+1,0)},"
                f" {nfun(i,j,1)}, {nfun(i+1,j,1)}, {nfun(i+1,j+1,1)}, {nfun(i,j+1,1)}")

    eb = 0
    L.append("*ELEMENT, TYPE=C3D8, ELSET=BOT")
    for j in range(ny):
        for i in range(nx):
            eb += 1
            L.append(f" {eb}," + hexc(nb, i, j))
    et = 1000000
    L.append("*ELEMENT, TYPE=C3D8, ELSET=TOP")
    for j in range(ny):
        for i in range(nx):
            et += 1
            L.append(f" {et}," + hexc(nt, i, j))

    # cohesive COH3D8: bottom face = bottom sublaminate top surface (k=1),
    # top face = top sublaminate bottom surface (k=0); bonded region x >= a0.
    L.append("*ELEMENT, TYPE=COH3D8, ELSET=COH")
    ce = 2000000
    for j in range(ny):
        for i in range(nx):
            if 0.5 * (xs[i] + xs[i + 1]) >= a0:
                ce += 1
                bot = (f" {nb(i,j,1)}, {nb(i+1,j,1)}, {nb(i+1,j+1,1)}, {nb(i,j+1,1)}")
                top = (f" {nt(i,j,0)}, {nt(i+1,j,0)}, {nt(i+1,j+1,0)}, {nt(i,j+1,0)}")
                L.append(f" {ce}," + bot + "," + top)

    L += ["**",
          "*SOLID SECTION, ELSET=BOT, MATERIAL=PLY",
          "*SOLID SECTION, ELSET=TOP, MATERIAL=PLY",
          "*SECTION CONTROLS, NAME=COHVISC, VISCOSITY=1.0e-5",
          "*COHESIVE SECTION, ELSET=COH, MATERIAL=INTERFACE, RESPONSE=TRACTION SEPARATION,"
          " THICKNESS=SPECIFIED, CONTROLS=COHVISC",
          " 1.0",
          "**",
          "*MATERIAL, NAME=PLY",
          "*ELASTIC",
          " 60.0e9, 0.30",
          "*MATERIAL, NAME=INTERFACE",
          "*ELASTIC, TYPE=TRACTION",
          " 1.0e14, 1.0e14, 1.0e14",
          "*DAMAGE INITIATION, CRITERION=QUADS",
          " 12.0e6, 18.0e6, 18.0e6",
          "*DAMAGE EVOLUTION, TYPE=ENERGY, MIXED MODE BEHAVIOR=BK, POWER=1.6",
          " 200.0, 600.0, 600.0"]

    # BCs: clamp far end (x=Lx) of both sublaminates; drive top near-end edge
    clamp = [nb(nx, j, k) for k in range(2) for j in range(NY)] + \
            [nt(nx, j, k) for k in range(2) for j in range(NY)]
    tipnodes = [nt(0, j, k) for k in range(2) for j in range(NY)]  # top arm, x=0 edge
    L.append("**")
    L.append("*NSET, NSET=CLAMP")
    for c0 in range(0, len(clamp), 8):
        L.append(" " + ", ".join(str(n) for n in clamp[c0:c0 + 8]))
    L.append("*NSET, NSET=TIP")
    for c0 in range(0, len(tipnodes), 8):
        L.append(" " + ", ".join(str(n) for n in tipnodes[c0:c0 + 8]))
    L += ["*BOUNDARY",
          " CLAMP, 1, 3, 0.0"]

    th = math.radians(theta_deg)
    uz = 6.0e-4 * math.cos(th); ux = 6.0e-4 * math.sin(th)   # mode I (z) + shear (x)
    L += ["**",
          "*STEP, NLGEOM=YES, INC=1000",
          "*STATIC",
          " 0.002, 1.0, 1.0e-8, 0.02",
          "*BOUNDARY",
          f" TIP, 1, 1, {ux:.6e}",
          " TIP, 2, 2, 0.0",
          f" TIP, 3, 3, {uz:.6e}",
          "*CONTROLS, ANALYSIS=DISCONTINUOUS",
          "*OUTPUT, FIELD",
          "*ELEMENT OUTPUT, ELSET=COH",
          " SDEG, STATUS",
          "*NODE OUTPUT",
          " U, RF",
          "*END STEP"]
    open(path, "w").write("\n".join(L) + "\n")
    return dict(nodes=2 * NB, els=2 * nx * ny, coh=ce - 2000000)


if __name__ == "__main__":
    import os
    here = os.path.dirname(os.path.abspath(__file__))
    c = gen_cure(os.path.join(here, "cfrtp_cure_residual.inp"))
    cve = gen_cure_ve(os.path.join(here, "cfrtp_cure_residual_ve.inp"))
    cx = gen_cryst_ve(os.path.join(here, "cfrtp_cryst_residual_ve.inp"))
    cp = gen_cryst_peek(os.path.join(here, "cfrtp_cryst_peek_validation.inp"))
    d = gen_delam(os.path.join(here, "cfrtp_delamination_mixedmode.inp"))
    d3 = gen_delam3d(os.path.join(here, "cfrtp_delamination_3d.inp"))
    s = gen_1elem_sanity(os.path.join(here, "cfrtp_1elem_sanity.inp"))
    print(f"cure    : {c['nodes']} nodes, {c['els']} C3D8 elements")
    print(f"cure_ve : {cve['nodes']} nodes, {cve['els']} C3D8 (viscoelastic UMAT)")
    print(f"cryst_ve: {cx['nodes']} nodes, {cx['els']} C3D8 (crystallization+VE UMAT)")
    print(f"cryst_pk: {cp['nodes']} nodes, {cp['els']} C3D8 (PEEK validation)")
    print(f"delam   : {d['nodes']} nodes, {d['els']} CPE4 + {d['coh']} COH2D4 elements")
    print(f"delam3d : {d3['nodes']} nodes, {d3['els']} C3D8 + {d3['coh']} COH3D8 elements")
    print(f"sanity  : {s['nodes']} nodes, {s['els']} C3D8 element")
